[pytest]
#--reruns = 2
addopts = -sv --alluredir ./report/data --clean-alluredir -n 2 --dist=loadfile

testpaths = ./testcases
;python_files = test_*.py
python_files = test_900_success*.py
#python_classes = Test*
python_functions = test_*

#pytest执行时将日志输出至控制台
log_cli = true
#日志格式
log_format = %(asctime)s %(levelname)s [%(name)s] [%(filename)s (%(funcName)s:%(lineno)d) - %(message)s]
#日期格式
log_date_format = %Y-%m-%d %H:%M:%S